### ISSUE TITLE
Instructions to compile?

### ISSUE THREAD

**Issue by RayBB** [Creator13/mapsnap#2]
Hello,

I'm trying to use this on a Mac and was wondering how to compile after installing dotnet 6?
I'm not familiar with the dotnet tooling so if you could point me towards the right direction to compile the binary I'd appreciate it.

Thanks!

**Comment by Creator13** [comment]
Hello! Sorry for the late reply. I'm not familiar with the mac ecosystem so I hope this works! The process should be mostly the same as compiling on Linux. Very simply, using the shell, you need to navigate to the folder with the files of the repository. Withing the root folder (or the folder the `OsmTimelapse.sln` file), you need to run the command `dotnet build --configuration Release`. When it's done, the built project will be in the folder `OsmTimelapse/bin/Release/net6.0`. The file you need to run is `mapsnap`. I'm not sure if this will work directly on a mac, but on linux you can just run `./mapsnap <commands...>`. If not, you should research this on your own. Hope this works!

The full official guide to building dotnet projects is here: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build

Ps. I've tried including mac and linux builds through using the publish feature of dotnet, but I'm not sure if they work. It would be great if you could try out the executable I've included in the latest release (https://github.com/Creator13/mapsnap/releases/tag/v1.0.2, the file called mapsnap-osx64.zip). You should be able to simply run the `mapsnap` file in the zip folder. If not, I'd love to know and figure out how to make it work!

**Comment by RayBB** [comment]
The mac build works great! Thanks for posting it :)

**Comment by Creator13** [comment]
Good to know, I'll keep posting them!
